name: valex_agro_audit_app
description: Valex Agro Audit App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  pull_to_refresh: 1.6.4-nullsafety.0
  firebase_core: ^1.0.3
  firebase_database: ^6.1.2
  firebase_storage: ^8.0.4
  cloud_firestore: ^1.0.6
  firebase_analytics: ^8.0.0
  shared_preferences: ^2.0.5
  flutter_calendar_carousel: ^2.0.1
  sqflite: ^2.0.0+3
  connectivity: ^3.0.3
  image_picker: ^0.7.4
  carousel_slider: 4.0.0-nullsafety.0
  pdf: ^3.2.0
  path_provider: ^2.0.1
  flutter_pdfview: ^1.1.0
  cached_network_image: ^3.0.0
  flutter_launcher_icons: ^0.9.0
  share: ^2.0.1
  fluttertoast: ^8.0.6
  http: ^0.13.1
  permission_handler: 7.0.0
  easy_localization: ^3.0.0
  google_sign_in: ^5.0.3
  googleapis: ^3.0.0
  googleapis_auth: any

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/appicon/
    - assets/translations/
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf